# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a660c841475c016c274241079029f128fd0e0fd3fb2510049be9a680adbaed15f551a53f531b2d5cc49ae64c9281c326084ed646f69f934bd979a3b135a5be9

test:
  secret_key_base: 75a30a24031214f2fa496875b386d0592aff089b7ff0efacf952f87b3a04995872f7e3be965e61054c3e875c0f297d11888dacfc3b6ff7ce008b7be0f32803e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
